# -*- coding: utf-8 -*-
"""Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1en8O6v-gYd6yS6lbVd6xN4ynKP7aXQeu
"""

def add(a,b):
  print("Sum=",add(a,b))