# -*- coding: utf-8 -*-
"""Diff.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134sJ5FAoCONXGaZwOJwJP5RdUL8EYjUr
"""

def sub(a,b):
  diff=a-b
  print("Diff={0}".format(diff))