# -*- coding: utf-8 -*-
"""divide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vl_74wudbAidv3AQaPPavRd89Miflsbs
"""

def div(a,b):
  div=a/b
  print("the division is : {0}",format(div))