# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vl_74wudbAidv3AQaPPavRd89Miflsbs
"""

def div(a,b):
  div=a/b
  printf("the division is : (0)",format(div))