# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKBVB30tTGqO0iWQ_o2bN0qLwaU7f_un
"""

import multiply
import add
import div
import sub


print("CALCULATOR")
n1=int(input("enter first number : "))
n2=int(input("enter second number : "))
print("1.add 2.sub 3.mul 4.div")
op=int(input("enter choice : "))
if op==1:
  add.add(n1,n2)
elif(op==2):
  sub.sub(n1,n2)
elif(op==3):
  multiply.mul(n1,n2) 
elif(op==4):
  div.div(n1,n2)
else:
  print("invalid choice")



# def add(a,b):
#   return a+b

# # print(add(1,2))

# print(summ.add(12,12))