# -*- coding: utf-8 -*-
"""multiply

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t_5ry6MhOU_RrG8Oj19-aam_nTZdH4Hv
"""

def mul(a,b):
  mult=a*b
  print("The product is : {0}".format(mult))